- project:
    templates:
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - publish-openstack-docs-pti
      - check-requirements
      - lib-forward-testing
      - lib-forward-testing-python3
    check:
      jobs:
        - openstack-tox-lower-constraints
    gate:
      jobs:
        - openstack-tox-lower-constraints
    post:
      jobs:
        - openstack-tox-cover
